[pytest]
markers =
    smoketest: marks test as providing a smoke test following deployment
    acceptance: marks test as providing an acceptance test
    openeo: marks test for OpenEO Building Block
    data_access: marks test for Data Access Building Block
    resource_discovery: marks test for Resource Discovery Building Block
    resource_registration: marks test for Resource Registration Building Block