[pytest]
markers =
    smoketest: marks test as providing a smoke test following deployment
    acceptance: marks test as providing an acceptance test
    openeo: marks test for OpenEO Building Block
    data_access: marks test for Data Access Building Block
    resource_discovery: marks test for Resource Discovery Building Block
    resource_registration: marks test for Resource Registration Building Block
    application_quality: marks test for Application Quality Building Block
    iam: marks test for IAM Building Block
    notification_automation: marks test for Notification and Automation Building Block
    workspace: marks test for Workspace Building Block
    oapip: marks test for Processing Building Block - OGC API Processes Engine
    mlops: marks test for MLOps Building Block
    resource_health: marks test for Resource Health Building Block