# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: ▶️ Run Smoke Tests

on:
  # via github UI
  workflow_dispatch:
  # # commits
  # push:
  #   branches:
  #     - deploy-*

jobs:
  run-smoke-tests:
    name: "Run Smoke Tests"
    uses: ./.github/workflows/run-tests.yaml
    secrets: inherit
    with:
      pytest-options: "-m smoketest"
