# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Run Tests

on:
  # via github UI
  workflow_dispatch:
  # following container rebuild
  workflow_run:
    workflows: ["Build Container"]
    types:
      - completed

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Prepare test environment
        run: |
          mkdir out
          cat - <<EOF > env-develop
          DOMAIN=develop.eoepca.org
          KEYCLOAK=keycloak.\${DOMAIN}
          EOAPI=eoapi.\${DOMAIN}
          MLOPS=sharinghub.\${DOMAIN}
          SCHEME=https
          EOF
      - name: Invoke pytest
        run: |
          docker run --rm -t \
            -e target=develop \
            -v ./env-develop:/work/test/.env.develop \
            -v ./out:/work/out \
            eoepca/system-test \
            pytest test -v --junit-xml=out/report.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            out/**/*.xml
